### ISSUE TITLE
How to use behave-restful plugin in a custom project?

### ISSUE THREAD

**Issue by anastasiiavlaskina** [behave-restful/behave-restful#40]
Hello!
Could you help me please with a question?
I'd like to use your framework in my behave based project for REST API testing.
I have my own steps, but I wanna use yours as well. How should I merge them?
A user documentation will be appreciated a lot=)

Thanks!

**Comment by CurroRodriguez** [comment]
Hi Anastasiia,

First of all, thank you for your interest in behave-restful. You are right; I need to spend some time working on the documentation, but I haven't had the time. I will do my best to start providing full documentation, as well as some other nice features.

Using behave-restful steps is not difficult, but there is some other setup that you will want to do. It seems that you are already using behave, which is great, so the easiest thing to do to integrate behave-restful is to create a python file in your steps folder, for example `behave_restful_steps.py`. In that file, you just add a single entry: `from behave_restful.lang import *`. This bring all the steps implemented in behave-restful into your test project, and you can use them.

You will need to modify the environment.py file to make sure behave-restful initializes correctly. There is a lot going on in behave-restful during initialization (support for hooks and definitions, initializing the context.session, etc.). The best thing to do if you already have an `environment.py` in your project is to follow these steps:
- Create a hooks folder at the same level as the steps folder (inside your features folder).
- Move your current environment.py into that folder. You will want to rename it to something else. The idea here is that behave-restful loads all the files in the hooks folder and registers all the environmental hooks in it, so they get called at the right time (before_all, before_feature, etc.). This also provides a mechanism to split the code on all those hooks, so that overtime, the code stays clean.
- Once you've moved your environment.py and renamed it, you will want to get the environment.py copy in this repo located at https://github.com/behave-restful/behave-restful/blob/master/features/environment.py, and place it in your features folder. If you look at the implementation, you'll see it initializes the context object through `BehaveRestfulApp`, which in turn also initializes other hooks implemented in the hooks folder.

There are additional functionality provided, but the best way to familiarize with the tool is to look at the features folder in this repo. That folder is a behave project using behave-restful, and might give you an idea on how to use it and the functionality available until I find some time to add documentation.

Let me know if you have any further questions, or if I can help you with something else, and thanks again for trying behave-restful. I use it in all my projects and it is an enjoyable tool.

Thanks,

**Comment by anastasiiavlaskina** [comment]
Hi Isaac!
Thank you for so detailed response and for the great work you've done creating this helpful tool!
The integration works for me now, and I'll continue using behave-restful, that's why some questions may come soon=)
Thank you!

Anastasiia

**Comment by CurroRodriguez** [comment]
Any time!
