### ISSUE TITLE
How to use basic authentication?

### ISSUE THREAD

**Issue by anastasiiavlaskina** [behave-restful/behave-restful#42]
Hi, Curro!

Could you help me please with the question how to use basic auth in requests?

I do
```python
Given a request url http://user:password@api-kore-api-server:80/cluster
```
but get 401 Unauthorized.
Does this syntax work?

I haven't found a possibility to add a header like here
```python
And I set "Authorization" header to "context.twitter_auth"
```
Thank you!

**Comment by CurroRodriguez** [comment]
All the steps implemented in `behave-resful` are based on the [`requests`](http://docs.python-requests.org/en/master/) module for Python. This means that you can replace the `context.session` object with a [`request.Session()`](http://docs.python-requests.org/en/master/user/advanced/#session-objects) object.

The way that I do it is by creating an authorization hook and implement the `before_all(context)` function to initialize my session object. The context object keeps a default session that can be used as an unauthorized session to test authorization failure scenarios:

```python
# in /hooks/autorization.py

from requests import Session
from requests.auth import HTTPBasicAuth

def before_all(context):
	context.authorized_session = Session(auth=HTTPBasicAuth('user', 'password'))
```

Then, I create two authorization steps:

```python
from behave import *

@given('an authorized session')
def step_impl(context):
	context.session = context.authorized_session
	
@given('an unauthorized session')
def step_impl(context):
	context.session = context.default_session
```

In the feature files, I usually define a background that sets the authorized session, since most scenarios will want to run authorized. The scenario that tests authorization uses the unauthorized session:

```gherkin
Feature: Tests for url http://my.server/api

	Background: We send authorized requests
		Given an authorized session
			And a request url http://my.server/api
		
	Scenario: Returns OK
		When the request sends GET
		Then the response status is OK
		
	Scenario: Requires authentication
		Given an unauthorized session
		When the request sends GET
		Then the response status is UNAUTHORIZED
```

I thought I've provided steps to set headers, but apparently I haven't. This is something I will add soon.

Let me know if you have any more questions, of if this answer helps so I can close the issue.

**Comment by upMKuhn** [comment]
Ok this is a serious blocker :fearful:

**Comment by CurroRodriguez** [comment]
@upMKuhn What's a serious blocker?

**Comment by upMKuhn** [comment]
My server expects a Bearer token via the Basic Auth Header. I can't set any headers, thus I can't make any valid request. :disappointed: 

Can you please add a quick fix under `request_builder set_header()` :)
and read the`context.headers` and forward it in the request_invoker for all http verbs.

**Comment by CurroRodriguez** [comment]
As I said before, this is planned, but I don't know when it will get done. Hopefully soon. 

Having said that, I also provided the solution. You can replace `context.session` with a `requests.Session()` object and add the headers you need. Follow the instructions I provided above.

**Comment by CurroRodriguez** [comment]
BTW, you would not want to set the headers in a step. Your credentials will be stored in plain text on your repo. Setting headers is a nice feature, but you should never use it to populate authentication headers.

**Comment by upMKuhn** [comment]
:+1:

**Comment by cookie220** [comment]
HI @CurroRodriguez Do you have any plan to fix the header problem?
