### ISSUE TITLE
example how to run live-server tests, e.g. bring up live flask as a fixture in behave?

### ISSUE THREAD

**Issue by beatthat** [behave-restful/behave-restful#45]
First off, thanks for putting together this great package!

I'd like to use behave-restful to run automated tests on a REST api written in Flask.

The thing I'm having troubling figuring out is how to automate tests that start the flask server, ideally either BEFORE_ALL or BEFORE_FEATURE.

All the examples I can find online for testing Flask with Behave seem to use a test-client python wrapper for the flask server rather than starting the server and testing over HTTP, e.g.

    https://behave.readthedocs.io/en/latest/usecase_flask.html

...I guess there's nothing really wrong with this, but if possible I prefer to have tests that are HTTP-end-to-end and to have the option to take the same tests I use for dev and point them at a live deployment of the service.

So far, the closest thing I've found to an example of setting up a live Flask server as a test fixture is the LiveServerTestCase class here:

    https://github.com/jarus/flask-testing/blob/master/flask_testing/utils.py

...but it's not for behave.

So wrapping up with my questions:

1) Do you have an example or recommendations for best way to automate running a live flask server with behave-restful tests?
2) If there is no such example, is the best option to make a live-flask behave fixture that forks a process, somehow waits/detects that flask has fully started and *then* runs the behave-feature tests?

Thanks in advance for your time and help. If you point me in the right direction and I get this working, I'd be happy to take a pass at updating the README to include instructions.

**Comment by CurroRodriguez** [comment]
@beatthat I also prefer to test flask applications through http and be able to run the same suite of tests against a live deployment. That's the whole point of writing behave-restful. I can provide you with an example, and I'll do so, but I need a little bit of time to put things together. I do that with all the applications I work on, but I have nothing readily available, so I need to go over some things.

**Comment by CurroRodriguez** [comment]
@beatthat Here is some information. Let me know if you have further questions:


The main idea is that you want to write an automation script that launches your Flask service and once it is up and running, starts the tests through `behave-restful`. I use [`bolt-ta`](https://bolt-task-automation.readthedocs.io/en/latest/), which is another OSS project I am working on to do the automation.

The nice thing is that `behave-restful` provides a bolt task to execute the feature tests. On the other hand, a Flask task is not available at the moment, so you have to create your own. Since I already implemented that task, here it is the code:

```python
# In bolt_flask.py (put this at the root of your project, or somewhere where it can be imported

import bolt.api as btapi

class StartFlaskServiceTask(btapi.Task):
    
    def __init__(self):
        super(StartFlaskServiceTask, self).__init__()
        self.process = None

    def tear_down(self):
        if self.process:
            self._terminate(self.process)
            
    def _configure(self):
        self.startup_script = self.config.get('startup-script')
        if not self.startup_script: raise StartupScriptNotSpecifiedError()

    def _execute(self):
        args = ['python', self.startup_script]
        self.process = self._popen_script(args)

    def _popen_script(self, args):
        return subprocess.Popen(args)

    def _terminate(self, process):
        process.terminate()
        
        
def register_tasks(registry):
	registry.register_task('start-flask', StartFlaskServiceTask())
        
        
class StartupScriptNotSpecifiedError(btapi.RequiredConfigurationError):
    def __init__(self):
        return super().__init__('startup-scripot')
       
```

The task launches a suprocess running your Flask application using your normal startup script that has been defined for your project. You provide a `register_tasks(registry)` function to register the task with bolt in the `boltfile.py` (see below).

Of course, you need to install `bolt-ta` in your environment:

```console
pip install bolt-ta
```

Then, you can create the `boltfile.py`

```python
# In boltfile.py

import bolt
import bolt_flask
import behave_restful.bolt_behave_restful as bbr

bolt.register_module_tasks(bolt_flask)
bolt.register_module_tasks(bbr)

# Bolt has a provided task sleep that is automatically registered

config = {
	'start-flask': {
		'startup-script': 'yourscript.py'
	},
	'sleep': {
		'duration': 5
	},
	'behave-restful': {
		'directory': 'features', # path to features folder
		'definition': 'yourdefinition',	# if you are using definitions for different environments
	}
}

# Register a task to invoke all that here:

bolt.register_task('test-features', ['start-flask', 'sleep', 'behave-restful'])
```

You import the `bolt_taks.py` module that I provided and the `bolt` integration in `behave-restful` and register both modules, so the tasks are available.

Then you configure the tasks exposing a `config` property as a dictionary with the options for each task (see [Your First Bolt File](https://bolt-task-automation.readthedocs.io/en/latest/using/getting_started.html#your-first-bolt-file)).

I usually add a `sleep` task between starting Flask and running the tests because Flask is launch on a separate process and it might take a few seconds to become available. You can play with the duration to insure the tests don't run before the service is available.

Now, you can run the following command to execute the tests:

```console
bolt test-features
```

There are a few things that you need to consider in your startup script, like the port in which your service runs. The reason is that if your CI/CD system doesn't isolate the environment (I have some builds running in Jenkins and Windows), you may run into circumstances where your tests fail because two separate branches are being tested trying to start Flask on the same port. In this case, the first one wins and the second one will fail because the process will be killed at the end of the first run.

I usually read the port from the environment and provide a default if not set. Bolt allows you to add an environment variable, or your CI/CD system might allow you to choose a random port and set it in the environment.

Let me know if this helps so I can close the issue.

**Comment by beatthat** [comment]
thanks for this @CurroRodriguez!

Using your answer, I was able to create an example that tests a flask api using bolt and behave-restful. I sent you the example as a pull request if you want to include it in the repo.

Thanks again for your help.
